### PR TITLE
ECR long-lived credentials - delete long lived credentials in CI env variables

### PR DESCRIPTION
**Pull request by davidread**
Thought we might usefully add this step in. I found that the CCQ team had also independently failed to do this step, so it's not obvious to folks

### CODE REVIEW

**Comment by davidread** [comment]
actually I think these steps need to be numbered (not `a)`) to render correctly as a list. I'll fix it if the text is welcomed

**Comment by jakemulley** [comment]
Thanks for this, @davidread. We have similar a similar step/note in [Deprecating long-lived credentials for modules](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/deprecating-long-lived-credentials.html#deprecating-long-lived-credentials-for-modules) for CircleCI that didn't make it across to this guide.

On GitHub Actions specifically, the action should fail if the job can't assume the role, and the manual removal of keys will be reverted for a namespace/repository as the secrets/variables are managed by the [module](https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials/blob/7a86e2d5c00fef844a2dd2a3ae47680e2abea711/main.tf#L97-L165) and will be re-added on a namespace apply or apply-live run. Therefore, I'm unsure whether we want to ask users to remove them specifically for testing, for a job that should fail anyway (and then the secrets/variables get re-added later).

The way to remove them would be to bump the module to [v6.0.0](https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials/releases/tag/6.0.0), but that removes the ability to support long-lived credentials when people move over more than one workflow, and it may be preferable for users if Cloud Platform remove these on team's behalf rather than asking them for an extra step of upgrading the module themselves.

What are your thoughts?

**Comment by davidread** [comment]
I think it's fine that CP team would do the step of upgrading the module to delete the access key in AWS. I think this PR seems like a useful step before that - to avoid the gotcha my team encountered, of still using the long-term credentials by virtue of them being a CI environment variable.

I think service teams are just following these instructions without thinking too hard or understanding, so I think benefit from it being laid out in detail like this.

**Comment by davidread** [comment]
Ah, I understand what you're saying about GitHub Actions now. Maybe this step is just useful for CircleCI folks

**Comment by davidread** [comment]
improved now @jakemulley

**Review by jakemulley — APPROVED** [review]

**Comment by jakemulley** [comment]
thanks @davidread 👍🏼

**Pull request merged**
